{% set name = "lb-telemetry" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lb-telemetry-{{ version }}.tar.gz
  sha256: 782ae2633309ab34e156e6484986275dfc503376ebd3b1cbd69b4946c21c08e8

build:
  entry_points:
    - lb-telemetry = lb_telemetry:lb_telemetry
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - setuptools >=61
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.6
    - lbplatformutils
    - logzero
    - requests

test:
  imports:
    - lb_telemetry
  commands:
    - pip check
    - lb-telemetry --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb/lb-telemetry
  summary: A utility for logging telemetry data from LHCb packages to MONIT
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - CameronMcClymont
